version: '3.8'
services:
  app:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/main
      - JWT_SECRET=supersecret
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
